[settings]
auto_install = true
exec_auto_install = true
experimental = true
lockfile = true
not_found_auto_install = true
task_run_auto_install = true
use_file_shell_for_executable_tasks = true

[env]
CLAUDE_ENV_FILE = "{{config_root}}/.claude/env.sh"

[tools]
markdownlint-cli2 = "latest"
"pipx:claudelint" = "latest"
"uv" = "latest"
biome = "2.3.6"
node = "lts"
act = "latest"
