{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "han-team.fullname" . }}
  labels:
    {{- include "han-team.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.sessionSecret }}
  session-secret: {{ .Values.secrets.sessionSecret | b64enc | quote }}
  {{- else }}
  session-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.githubClientId }}
  github-client-id: {{ .Values.secrets.githubClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.githubClientSecret }}
  github-client-secret: {{ .Values.secrets.githubClientSecret | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) .Values.externalDatabase.password }}
  postgres-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
