[test]
root = "test"
preload = ["./test/setup.ts"]
coverage = true
# coverageThreshold = 0.55
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = "../han-native/index.js"

[install]
auto = "auto"